# VALUES result:
# int8 RECONFIGURATION_OK=1
# int8 RECONFIGURATION_FAILED=0
# int8 RECONFIGURATION_UNKNOWN=-1
# int8 GENERAL_ERROR=-2

# VALUES desired_configuration_name:
# string LOW_POWER_CONFIGURATION_NAME=“low_power”
# string STANDARD_CONFIGURATION_NAME=“standard”

# goal
string desired_configuration_name
---
# result
int8 result
---
#feedback
